version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: posref1
    ports:
      - "8001:80"
    volumes:
      - ./test:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - .:/usr/share/nginx/html
