version: "3.7"
services:
    web: 
        image: ranur/codeigniter:3.11-sessions
        volumes:
            - .:/app/myapp
        ports:
            - 8001:8000
        depends_on:
            - mariadb
        container_name: posref1
    mariadb:
        image: docker.io/bitnami/mariadb:10.3
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_DATABASE=db_mariaDB
        ports:
            - 3006:3306
        container_name: mariaDB
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mariadb
        ports:
            - 8005:80
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: 12345
        container_name: phpmyadmin
